package com.rsc_games.sledge;

import com.rsc_games.sledge.lib.Version;

// TODO: Auto-generated by sledge.
public class VersionHeader {
    public static final Version VERSION = new Version(3, 0, 0, 6);
    public static final String SUFFIX = "-dev";
}
